//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneVote {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneVote.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ballot has already been submitted..
        /// </summary>
        public static string AboutBallotHasBeeSubmitted {
            get {
                return ResourceManager.GetString("AboutBallotHasBeeSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera not found!  The camera is needed for your signature.  This device cannot be used for voting..
        /// </summary>
        public static string AboutCameraWarning {
            get {
                return ResourceManager.GetString("AboutCameraWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote for your candidates in the 2020 Presidential Election.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election Voting App..
        /// </summary>
        public static string AboutHeading1 {
            get {
                return ResourceManager.GetString("AboutHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string AboutLearnMore {
            get {
                return ResourceManager.GetString("AboutLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.e2e-viv.org.
        /// </summary>
        public static string AboutLearnMoreUrl {
            get {
                return ResourceManager.GetString("AboutLearnMoreUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Election . . . .
        /// </summary>
        public static string AboutLoadingElectionMessage {
            get {
                return ResourceManager.GetString("AboutLoadingElectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter your SSN!.
        /// </summary>
        public static string AboutNeedsSSN {
            get {
                return ResourceManager.GetString("AboutNeedsSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting has not started yet or have already closed..
        /// </summary>
        public static string AboutPollsNotOpen {
            get {
                return ResourceManager.GetString("AboutPollsNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting is between {0} and {1} local time.
        /// </summary>
        public static string AboutPollsOpenDateRange {
            get {
                return ResourceManager.GetString("AboutPollsOpenDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Election QR Code.
        /// </summary>
        public static string AboutScanQR {
            get {
                return ResourceManager.GetString("AboutScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try connect again.
        /// </summary>
        public static string AboutTryAgain {
            get {
                return ResourceManager.GetString("AboutTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote!.
        /// </summary>
        public static string AboutVote {
            get {
                return ResourceManager.GetString("AboutVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load election by scanning QR Code!.
        /// </summary>
        public static string AboutWaitMessage {
            get {
                return ResourceManager.GetString("AboutWaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection is required to vote!.
        /// </summary>
        public static string AppInternetMessage {
            get {
                return ResourceManager.GetString("AppInternetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot has already been submitted..
        /// </summary>
        public static string BallotAlreadySubmitted {
            get {
                return ResourceManager.GetString("BallotAlreadySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find ONE face in photo..
        /// </summary>
        public static string FoundFacesFailed {
            get {
                return ResourceManager.GetString("FoundFacesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ItemsPageDisplayAlertTitle {
            get {
                return ResourceManager.GetString("ItemsPageDisplayAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your vote has been successfully cast.\nYour name is: {0}\nYour confirmation is {1}.
        /// </summary>
        public static string ItemsPageSubmittalConfirmation {
            get {
                return ResourceManager.GetString("ItemsPageSubmittalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem and the ballot was not successfully cast.  Please redo your vote..
        /// </summary>
        public static string ItemsPageSubmittalProblem {
            get {
                return ResourceManager.GetString("ItemsPageSubmittalProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ballot votes are being encrypted to ensure that it cannot be tampered with prior to reaching the main voting server.  This can take anywhere from 2 to 30 minutes!  Please be patient..
        /// </summary>
        public static string ItemsViewModelEncryptionMessage {
            get {
                return ResourceManager.GetString("ItemsViewModelEncryptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Shot.
        /// </summary>
        public static string ItemsViewModelHeadShot {
            get {
                return ResourceManager.GetString("ItemsViewModelHeadShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting Nonce: {0}.
        /// </summary>
        public static string ItemsViewmodelProgressUpdate {
            get {
                return ResourceManager.GetString("ItemsViewmodelProgressUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not voted for anyone..
        /// </summary>
        public static string NoVotesCast {
            get {
                return ResourceManager.GetString("NoVotesCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot can now be submitted..
        /// </summary>
        public static string ReviewBallotAlertMsg {
            get {
                return ResourceManager.GetString("ReviewBallotAlertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballot choice option.
        /// </summary>
        public static string ReviewBallotAlertTitle {
            get {
                return ResourceManager.GetString("ReviewBallotAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section: .
        /// </summary>
        public static string ReviewBallotSection {
            get {
                return ResourceManager.GetString("ReviewBallotSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your authorization code here.  Only you know what the code is.  It was a code that you agreed to when registering to vote.  It might be your SSN, or the answer to one of your security questions, or your street address..
        /// </summary>
        public static string SubmitAuthMessage {
            get {
                return ResourceManager.GetString("SubmitAuthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
