//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Election {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Election.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Category_CategoryTypeUnknownEnum {
            get {
                return ResourceManager.GetString("Category-CategoryTypeUnknownEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category View.
        /// </summary>
        public static string Category_Header_Label {
            get {
                return ResourceManager.GetString("Category-Header-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading:.
        /// </summary>
        public static string Category_Heading {
            get {
                return ResourceManager.GetString("Category-Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information:.
        /// </summary>
        public static string Category_Information {
            get {
                return ResourceManager.GetString("Category-Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Senate Race.
        /// </summary>
        public static string Category_IsSenateRace {
            get {
                return ResourceManager.GetString("Category-IsSenateRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Judge Position.
        /// </summary>
        public static string Category_JudgePosition {
            get {
                return ResourceManager.GetString("Category-JudgePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTitle:.
        /// </summary>
        public static string Category_SubTitle {
            get {
                return ResourceManager.GetString("Category-SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Category_Title {
            get {
                return ResourceManager.GetString("Category-Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Type:.
        /// </summary>
        public static string Category_Type {
            get {
                return ResourceManager.GetString("Category-Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds new category to election..
        /// </summary>
        public static string Election_AddButtonToolTip {
            get {
                return ResourceManager.GetString("Election-AddButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow re-submittals..
        /// </summary>
        public static string Election_AllowUpdates {
            get {
                return ResourceManager.GetString("Election-AllowUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string Election_CategoryType {
            get {
                return ResourceManager.GetString("Election-CategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election Date:.
        /// </summary>
        public static string Election_Date {
            get {
                return ResourceManager.GetString("Election-Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Election_Description {
            get {
                return ResourceManager.GetString("Election-Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves selected category down on position..
        /// </summary>
        public static string Election_DnButtonToolTip {
            get {
                return ResourceManager.GetString("Election-DnButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Election View.
        /// </summary>
        public static string Election_Header {
            get {
                return ResourceManager.GetString("Election-Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polls Close Date:.
        /// </summary>
        public static string Election_PollsClose {
            get {
                return ResourceManager.GetString("Election-PollsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polls Open Date:.
        /// </summary>
        public static string Election_PollsOpen {
            get {
                return ResourceManager.GetString("Election-PollsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed selected category and associated Tickets from Election, no undo!.
        /// </summary>
        public static string Election_RemoveButtonToolTip {
            get {
                return ResourceManager.GetString("Election-RemoveButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Election:.
        /// </summary>
        public static string Election_Select_Election {
            get {
                return ResourceManager.GetString("Election-Select-Election", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorts Legislative by District or Judicial By County.
        /// </summary>
        public static string Election_SortAlphaDown {
            get {
                return ResourceManager.GetString("Election-SortAlphaDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves selected category up one position..
        /// </summary>
        public static string Election_UpButtonToolTip {
            get {
                return ResourceManager.GetString("Election-UpButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds new Ticket to current Category..
        /// </summary>
        public static string Ticket_AddButtonToolTip {
            get {
                return ResourceManager.GetString("Ticket-AddButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Name/Description:.
        /// </summary>
        public static string Ticket_CandidateName {
            get {
                return ResourceManager.GetString("Ticket-CandidateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves selected Ticket down one position..
        /// </summary>
        public static string Ticket_DnButtonToolTip {
            get {
                return ResourceManager.GetString("Ticket-DnButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legislative Position:.
        /// </summary>
        public static string Ticket_LegislativePosition {
            get {
                return ResourceManager.GetString("Ticket-LegislativePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        public static string Ticket_Party {
            get {
                return ResourceManager.GetString("Ticket-Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes Ticket from current category - No Undo!.
        /// </summary>
        public static string Ticket_RemoveButtonToolTip {
            get {
                return ResourceManager.GetString("Ticket-RemoveButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Title:.
        /// </summary>
        public static string Ticket_SubTitle {
            get {
                return ResourceManager.GetString("Ticket-SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Ticket_Unknown {
            get {
                return ResourceManager.GetString("Ticket-Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves selected Ticket up one position..
        /// </summary>
        public static string Ticket_UpButtonToolTip {
            get {
                return ResourceManager.GetString("Ticket-UpButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets_Header {
            get {
                return ResourceManager.GetString("Tickets-Header", resourceCulture);
            }
        }
    }
}
